I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/classroom.rpy", line 2, in script
    show bg classroom with map_fade
  File "game/script/classroom.rpy", line 2, in <module>
    show bg classroom with map_fade
NameError: name 'map_fade' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/classroom.rpy", line 2, in script
    show bg classroom with map_fade
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\ast.py", line 1352, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script/classroom.rpy", line 2, in <module>
    show bg classroom with map_fade
NameError: name 'map_fade' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Break: The Rematch 0.01a
Sun Dec 23 17:47:27 2018
